common:
  output_directory: {{output_directory}} # Must be overwritten
  constants: # Must be overwritten
    source: {{source}}
    target: {{target}}
    source_fullname: {{source_fullname}}
    target_fullname: {{target_fullname}}
    nllb_source: {{nllb_source}}
    nllb_target: {{nllb_target}}
    cache_dir: {{cache_dir}}

steps:
  
  - type: preprocess
    parameters:
      inputs:
        - !varstr "{source}-{target}.{source}.gz"
        - !varstr "{source}-{target}.{target}.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.preprocessed.gz"
        - !varstr "{source}-{target}.{target}.preprocessed.gz"
      preprocessors:
        - RegExpSub:
            patterns: 
              - ['[‘’]', "'", 0, []]
              - ['[“”]', "\"", 0, []]
              - ['Bali:', "", 0, []]
              - ['Balinese:', "", 0, []]
              - ['Minangkabau:', "", 0, []]
              - ['\(\d+:\d+\)', "", 0, []]
        - WhitespaceNormalizer: {}


  - type: remove_duplicates
    parameters:
      inputs:
        - !varstr "{source}-{target}.{source}.preprocessed.gz"
        - !varstr "{source}-{target}.{target}.preprocessed.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.preprocessed-dup.gz"
        - !varstr "{source}-{target}.{target}.preprocessed-dup.gz"
  
  - type: filter
    parameters:
      inputs:
        - !varstr "{source}-{target}.{source}.preprocessed-dup.gz"
        - !varstr "{source}-{target}.{target}.preprocessed-dup.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.filtered.gz"
        - !varstr "{source}-{target}.{target}.filtered.gz"
      filters:
        # - TerminalPunctuationFilter:
        #     threshold: -2
        - LengthFilter:
            min_length: 3
            max_length: 100
            unit: word
        - LengthRatioFilter:
            threshold: 2
            unit: word
        - LongWordFilter:
            threshold: 20
        - RingFilter:
            threshold: 0.33
          module: filters
        - IdenticalStringsFilter: {}
          module: filters
        - PunctuationFilter:
            threshold: 0.2
          module: filters
        - NumberFilter:
            threshold: 0.2
          module: filters
        - LaserEmbeddingFilter:
            languages:
              - !varstr "{nllb_source}"
              - !varstr "{nllb_target}"
            threshold: 0.6
          module: filters
  
  - type: preprocess
    parameters:
      inputs:
        - !varstr "{source}-{target}.{source}.filtered.gz"
        - !varstr "{source}-{target}.{target}.filtered.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.aligned.gz"
        - !varstr "{source}-{target}.{target}.aligned.gz"
      preprocessors:
        - AlignGPTCleaner:
            source_language: !varstr "{source_fullname}"
            target_language: !varstr "{target_fullname}"
          module: filters

  - type: split
    parameters:
      divisor: 2
      seed: 0
      inputs:
        - !varstr "{source}-{target}.{source}.aligned.gz"
        - !varstr "{source}-{target}.{target}.aligned.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.final.gz"
        - !varstr "{source}-{target}.{target}.final.gz"
      outputs_2:
        - !varstr "{target}-{source}.{source}.final.gz"
        - !varstr "{target}-{source}.{target}.final.gz"
    
    # SPLIT source-target into train test validation

  - type: split
    parameters: 
      divisor: 10
      threshold: 9
      seed: 1
      inputs: 
        - !varstr "{source}-{target}.{source}.final.gz"
        - !varstr "{source}-{target}.{target}.final.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.train.gz"
        - !varstr "{source}-{target}.{target}.train.gz"
      outputs_2:
        - !varstr "{source}-{target}.{source}.temp.gz"
        - !varstr "{source}-{target}.{target}.temp.gz"
  
  - type: split # split source-target into train test validation
    parameters: 
      divisor: 2
      seed: 2
      inputs: 
        - !varstr "{source}-{target}.{source}.temp.gz"
        - !varstr "{source}-{target}.{target}.temp.gz"
      outputs:
        - !varstr "{source}-{target}.{source}.test.gz"
        - !varstr "{source}-{target}.{target}.test.gz"
      outputs_2:
        - !varstr "{source}-{target}.{source}.valid.gz"
        - !varstr "{source}-{target}.{target}.valid.gz"
  
  # SPLIT target-source into train test validation

  - type: split
    parameters: 
      divisor: 10
      threshold: 9
      seed: 3
      inputs: 
        - !varstr "{target}-{source}.{source}.final.gz"
        - !varstr "{target}-{source}.{target}.final.gz"
      outputs:
        - !varstr "{target}-{source}.{source}.train.gz"
        - !varstr "{target}-{source}.{target}.train.gz"
      outputs_2:
        - !varstr "{target}-{source}.{source}.temp.gz"
        - !varstr "{target}-{source}.{target}.temp.gz"
  
  - type: split # split source-target into train test validation
    parameters: 
      divisor: 2
      seed: 4
      inputs: 
        - !varstr "{target}-{source}.{source}.temp.gz"
        - !varstr "{target}-{source}.{target}.temp.gz"
      outputs:
        - !varstr "{target}-{source}.{source}.test.gz"
        - !varstr "{target}-{source}.{target}.test.gz"
      outputs_2:
        - !varstr "{target}-{source}.{source}.valid.gz"
        - !varstr "{target}-{source}.{target}.valid.gz"
      
      